version: "3.2"

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: radius
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - freeradius-admin-network
  freeradius:
    build:
      context: ./freeradius
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    networks:
      - freeradius-admin-network
    volumes:
      - type: volume
        source: dictionaries
        target: /usr/share/freeradius
        read_only: true
  app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:5000"
    depends_on:
      - db
      - freeradius
    environment:
      DATABASE_SERVER: db
      DATABASE_USER: radius
      DATABASE_PASSWORD: radpass
      DATABASE_NAME: radius
    networks:
      - freeradius-admin-network
    volumes:
      - type: volume
        source: dictionaries
        target: /usr/share/freeradius
        read_only: true

networks:
  freeradius-admin-network:

volumes:
  dictionaries:
