version: "3"

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: radius
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
